from prac_06.programming_language import ProgrammingLanguage
ruby = ProgrammingLanguage("Ruby", "Dynamic", True, 1995)
python = ProgrammingLanguage("Python", "Dynamic", True, 1991)
visual_basic = ProgrammingLanguage("Visual Basic", "Static", False, 1991)
print(ruby)
print(python)
print(visual_basic)
print("The dynamically typed languages are:")
thefile = ProgrammingLanguage("Ruby", "Dynamic")
ruby.is_dynamic()
python.is_dynamic()
visual_basic.is_dynamic()